import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { v4 as uuidv4 } from "uuid";
import styles from "../styles/Home.module.css";

import dynamic from "next/dynamic";

// import { Map } from "../component/Map";

export async function getServerSideProps() {
  const ACCESS_TOKEN = process.env.NEXT_MAPBOX;
  console.log(ACCESS_TOKEN);

  return {
    props: {
      ACCESS_TOKEN,
    },
  };
}

interface Cords {
  lat: number;
  long: number;
}

const Map: any = dynamic(() => import("../components/Map") as any, {
  ssr: false,
});

export default function Home({ ACCESS_TOKEN }: any) {
  const [startCords, setStartCords] = useState<Cords>();

  function success(pos: any) {
    var crd = pos.coords;

    const newCords: Cords = {
      lat: crd.latitude,
      long: crd.longitude,
    };

    setStartCords(newCords);

    // console.log("Your current position is:");
    // console.log(`Latitude : ${crd.latitude}`);
    // console.log(`Longitude: ${crd.longitude}`);
    // console.log(`More or less ${crd.accuracy} meters.`);
  }

  function error(err: any) {
    console.warn(`ERROR(${err.code}): ${err.message}`);

    return false;
  }

  var options = {
    enableHighAccuracy: true,
    timeout: 5000,
    maximumAge: 0,
  };

  useEffect(() => {
    const currentCords = navigator.geolocation.getCurrentPosition(
      success,
      error,
      options
    );
    console.log(currentCords);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`h-screen w-screen`}>
        <h1>Find a vaccine in Victoria</h1>
        <div>
          <h2>Can I get the vaccine?</h2>
          <div>
            <h4>Are you over 50?</h4>
            <div>Result</div>
          </div>
          <form>
            {/* <label>Location</label> */}
            {/* <input>Location</input> */}
            <button>Search</button>
          </form>
        </div>
        <Map
          key={uuidv4()}
          accessToken={ACCESS_TOKEN}
          startCords={startCords}
        />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={``}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
